"""Adds zipcode to user table

Revision ID: edbda8ed9135
Revises: 5d13d87f94b8
Create Date: 2018-05-08 18:57:17.926356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbda8ed9135'
down_revision = '5d13d87f94b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_zip'), 'user', ['zip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_zip'), table_name='user')
    op.drop_column('user', 'zip')
    # ### end Alembic commands ###
